### ISSUE TITLE
Symfony

### ISSUE THREAD

**Issue by ikerib** [WeCodeSign/nuevos-episodios-e-invitades#1]
Framework php muy extendido con gran comunidad desymfony.com por ejemplo.

Para la entrevista  Javier Eguiluz ( https://github.com/javiereguiluz) , actualmente trabajando en la empresa creadora del framework

**Comment by IgnaciodeNuevo** [comment]
Hola @ikerib lamentablemente y debido a que el Podcast está orientado a Front-end, Diseño Web y UX y que nuestros conocimientos son relacionados con el tema creo que vamos a seguir con lo planeado.

Mil gracias por participar e intentar dar ideas, sin duda si hablásemos sobre Back lo tendríamos muy en cuenta.
