### ISSUE TITLE
Sugerencias de temas

### ISSUE THREAD

**Issue by andresmeri** [WeCodeSign/nuevos-episodios-e-invitades#2]
Hola, 
Primero, enhorabuena por el programa y por todo el altruismo.
Cabe decir que no he escuchado todos los podcasts y seguramente algún tema se ha tocado ya.
Sugerencias para un mini:
- ¿Cómo el mundo exterior ve a los desarrolladores web? A pesar de que el diseño y el desarrollo web esta en todas partes, para mucha gente estos profesionales son "informáticos". La tv ha hecho mucho daño al respecto. Series que hablan del tema (Silicon Valley, IT crowd, Mr. Robot) ¿Sugerencias?
- ¿Qué opináis sobre Material Design?

Felicidades de nuevo y adelante!

+ Andrés

**Comment by IgnaciodeNuevo** [comment]
Añadidos, muchas gracias :)

El de como ve el mundo a los desarrolladores me parece muy interesante.

**Comment by luispastendev** [comment]
Hola gran trabajo ignacio sigo los podcast desde hace tiempo y me gustaría que reanudaras el trabajo 

Con respecto a temas estaría bueno abordar cosas de freelancers como:

- como comenzar a buscar clientes?
- como cotizar proyectos?
- publicidad en redes sociales

Muchas gracias !!

**Comment by IgnaciodeNuevo** [comment]
Perdona @luispastendev, me temo que ahí no voy a poder ayudarte porque jamás he sido freelance y no creo que sea bueno que de consejos sin conocimiento del tema.
