### ISSUE TITLE
Sugerencias de entrevistados

### ISSUE THREAD

**Issue by tipoqueno** [WeCodeSign/nuevos-episodios-e-invitades#3]
Hola Ignacio y Carmen. Felicitaciones por el Podcast, necesitamos mucho contenido en español sobre estas temáticas.

Mis sugerencias para entrevistar: 

- Ignacio Anaya: Full Stack Developer enfocado en JS. Impulsor de la comunidad Vuenos Aires (Vue.js en Buenos Aires), creador del curso avanzado de Vue.js en Platzi.
Github: https://github.com/ianaya89
Video: https://www.youtube.com/watch?v=3825H8NdstI

- Evangelina Ferreira: Front-End developer y profesora. Parte del equipo de la CSSConfAr 
Github: https://github.com/evaferreira
Video: https://www.youtube.com/watch?v=GvT6tXa5i3w

Un saludo!

**Comment by IgnaciodeNuevo** [comment]
Lo primero disculpa el retraso @tipoqueno pero por falta de tiempo a partir de enero WeCodeSign quedará en stand by y dejaremos de grabar episodios.

De todos modos y pos si acaso continuásemos en un futuro mil gracias por el aporte.

**Comment by tipoqueno** [comment]
No pasa nada. Una lástima que no puedan seguir por el momento.
Yo tengo ganas de arrancar algo similar, veré qué puedo hacer.

Un gusto!
